---
- name: Install Apache Web Service
  hosts: all
  gather_facts: false
  tasks:
    - name: Install the required package
      yum:
        name: httpd
        state: latest

    - name: Start the service
      service:
        name: httpd
        state: started
        enabled: true
