---
 - name: Commands Over Oracle Data Base
   hosts: all
   # become: true
   gather_facts: false
   collections:
     - ibre5041.ansible_oracle_modules
   tasks:
   
    # - name: install dependency
    #   ansible.builtin.pip:
    #     name: cx_Oracle

    - name: execute oracle command
      ibre5041.ansible_oracle_modules.oracle_sql:
        mode: sysdba
        sql: "SELECT * FROM v$version"
        service_name: cdb1
        oracle_home: /u01/app/oracle/product/19.0.0/dbhome_1/
      register: _oracle_dba_users

    # - name: Create "Employees" Data Base
    #   shell: echo 'CREATE DATA BASE employees;' | sqlplus / as sysdba

    # - name: Create "Names" Table on "Employees" Data Base
    #   shell: echo 'CREATE TABLE names(firstName varchar(255), lastName varchar(255));' | sqlplus / as sysdba